name: Auto workflow assignment for RSE102
on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install python style checker"
        run: pip install black
      - name: "Check python style"
        run: black --check .
  test:
    needs: style_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install numpy package"
        run: pip install numpy
      - name: "Install matplotlib package"
        run: python -m pip install -U matplotlib
      - name: "Install pytest package"
        run: pip install -U pytest
      - name: "Run test with pytest"
        run: python -m pytest
      - name: "Install coverage package"
        run: pip install coverage
      - name: "Collect coverage info"
        run: coverage run -m pytest
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: my-coverage
          path: .coverage
          retention-days: 1
  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Download a single artifact"
        uses: actions/download-artifact@v2
        with:
          name: my-coverage
      - name: "Install coverage package"
        run: pip install -U coverage
      - name: "Generate coverage report"
        run: coverage report -m
      - name: "Save report in xml"
        run: coverage xml
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: my-coverage-xml
          path: coverage.xml
          retention-days: 14