name: Auto workflow assignment for RSE102
on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install python style checker"
        run: pip install black
      - name: "Check python style"
        run: black --check .
  test:
    needs: style_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Run test with pytest"
        run: python -m pytest
      - name: "Install coverage package"
        run: pip install coverage
      - name: "Collect coverage info"
        run: coverage report -m

